---
baseurl: "http://matt.guindin.com"
contentdir: "content"
publishdir: "app/views/posts"
staticdir: "public"
indexes:
  category: "categories"
title: "Matt's Thoughts on Random Stuff"
permalinks:
  post: /:year/:month:title/
...